<div class="container h-100">
    <div class="row align-items-center h-100">
        <div class="col-6 mx-auto">
            <div class="panel">
                <div class="panel-title">
                    <h5>Please Sign In</h5>
                </div>
                <div class="panel-body">
                    <form action="" method="post">
                        <div class="form-group error">
                            <label>Email address</label>
                            <input type="email" class="form-control" placeholder="Enter email">
                            <small class="form-text">We'll never share your email with anyone else.</small>
                        </div>
                        <div class="form-group">
                            <label>Password</label>
                            <input type="email" class="form-control" placeholder="Enter email">
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <hr class="hr-text" data-content="Or">
                        <button type="submit" class="btn btn-primary">Sign in with GitHub</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
