<?php declare(strict_types=1); ?>
<?php /** @var \PeeHaa\AwesomeFeed\Form\Authentication\Login $loginForm */ ?>
<div class="container h-100">
    <div class="row align-items-center h-100">
        <div class="col-6 mx-auto">
            <div class="panel">
                <div class="panel-title">
                    <h5><?= $this->translate('login.title'); ?></h5>
                </div>
                <div class="panel-body">
                    <form action="<?= $this->url('processGitHubLogin'); ?>" method="post">
                        <input type="hidden" name="csrfToken" value="<?= $loginForm['csrfToken']->getValue(); ?>">
                        <button type="submit" class="btn btn-primary btn-block"><?= $this->translate('login.form.github.submit'); ?></button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
