<?php declare(strict_types=1); ?>
<?php /** @var string $content; */ ?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title><?= $this->translate('site.title'); ?></title>
        <link href="https://fonts.googleapis.com/css?family=Calibri:400,700,400italic,700italic" rel="stylesheet">
        <link rel="stylesheet" href="/css/bundle.min.css">
    </head>
    <body>
        <?= $content; ?>
        <script src="/js/bundle.min.js"></script>
    </body>
</html>
