<?php declare(strict_types=1); ?>
<?php /** @var string $content; */ ?>
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title><?= $this->translate('site.title'); ?></title>
        <link href="https://fonts.googleapis.com/css?family=Calibri:400,700,400italic,700italic" rel="stylesheet">
        <link rel="stylesheet" href="/css/bundle.min.css">
        <link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">
        <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
        <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
        <link rel="manifest" href="/site.webmanifest">
        <meta name="msapplication-TileColor" content="#da532c">
        <meta name="theme-color" content="#ffffff">
    </head>
    <body>
        <?php if ($this->gateKeeper->isAuthorized()) { ?>
            <?= $this->render('/layout/header.phtml'); ?>
        <?php } ?>
        <?= $content; ?>
        <script src="/js/bundle.min.js"></script>
    </body>
</html>
