<?php declare(strict_types=1); ?>
<?php /** @var \PeeHaa\AwesomeFeed\Feed\Collection $overview */ ?>
<div class="panel">
    <div class="panel-title">
        <h5><?= $this->translate('feed.overview.title'); ?></h5>
    </div>
    <div class="panel-body">
        <table class="table feeds">
            <tr>
                <th><?= $this->translate('feed.overview.table.name'); ?></th>
                <th><?= $this->translate('feed.overview.table.createdBy'); ?></th>
                <th><?= $this->translate('feed.overview.table.url'); ?></th>
                <th class="repositories"><?= $this->translate('feed.overview.table.repositories'); ?></th>
                <th class="releases"><?= $this->translate('feed.overview.table.releases'); ?></th>
                <th class="actions">&nbsp;</th>
            </tr>
            <?php if (!count($overview)) { ?>
                <tr>
                    <td colspan="6"><?= $this->translate('feed.overview.table.noResults'); ?></td>
                </tr>
            <?php } else { ?>
                <?php foreach ($overview as $feed) { ?>
                    <tr data-id="<?= $feed->getId(); ?>">
                        <td><?= $this->escape($feed->getName()); ?></td>
                        <td>
                            <a href="<?= $this->escape($feed->getCreatedBy()->getUrl()); ?>" target="_blank">
                                <?= $this->escape($feed->getCreatedBy()->getUsername()); ?>
                            </a>
                        </td>
                        <td><a href="<?= $this->escape($feed->getSlug()); ?>" target="_blank"><?= $this->escape($feed->getSlug()); ?></a></td>
                        <td class="repositories"><?= count($feed->getRepositories()); ?></td>
                        <td class="releases"><?= count($feed->getReleases()); ?></td>
                        <td class="actions">
                            <a href="<?= $this->escape($this->url('editFeed', ['id' => $feed->getId(), 'slug' => $feed->getSlug()])); ?>" class="btn btn-primary">
                                <i class="icon-pencil"></i>
                            </a>
                            <a href="<?= $this->escape($this->url('deleteFeedConfirmation', ['id' => $feed->getId(), 'slug' => $feed->getSlug()])); ?>" class="btn btn-danger delete-feed">
                                <i class="icon-cross"></i>
                            </a>
                        </td>
                    </tr>
                <?php } ?>
            <?php } ?>
        </table>
    </div>
</div>
